//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.07 at 09:25:26 PM IST 
//


package com.slabs.expense.tracker.core.db.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.slabs.expense.tracker.core.db.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExpenseCategory_QNAME = new QName("http://slabs.com/expense/tracker/core/db/entity", "ExpenseCategory");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.slabs.expense.tracker.core.db.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExpenseCategory }
     * 
     */
    public ExpenseCategory createExpenseCategory() {
        return new ExpenseCategory();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpenseCategory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://slabs.com/expense/tracker/core/db/entity", name = "ExpenseCategory")
    public JAXBElement<ExpenseCategory> createExpenseCategory(ExpenseCategory value) {
        return new JAXBElement<ExpenseCategory>(_ExpenseCategory_QNAME, ExpenseCategory.class, null, value);
    }

}
