
/* INCOMETYPE  - Start */
INSERT INTO EXPENSETRACKER.INCOMETYPE(INCOMETYPE, DESCRIPTION) VALUES ('Salary', 'Salary');
INSERT INTO EXPENSETRACKER.INCOMETYPE(INCOMETYPE, DESCRIPTION) VALUES ('Business', 'Business');
INSERT INTO EXPENSETRACKER.INCOMETYPE(INCOMETYPE, DESCRIPTION) VALUES ('Gift', 'Gift');
INSERT INTO EXPENSETRACKER.INCOMETYPE(INCOMETYPE, DESCRIPTION) VALUES ('Others', 'Others');
/* INCOMETYPE  - End */


/* EXPENSETYPE - Start */
INSERT INTO EXPENSETRACKER.EXPENSETYPE(EXPTYPE, DESCRIPTION) VALUES ('Cash', 'Cash');
INSERT INTO EXPENSETRACKER.EXPENSETYPE(EXPTYPE, DESCRIPTION) VALUES ('Credit Card', 'Credit Card');
INSERT INTO EXPENSETRACKER.EXPENSETYPE(EXPTYPE, DESCRIPTION) VALUES ('Debit Card', 'Debit Card');
INSERT INTO EXPENSETRACKER.EXPENSETYPE(EXPTYPE, DESCRIPTION) VALUES ('Net Banking', 'Net Banking');
/* EXPENSETYPE - End */

/* CURRENCY - Start */
INSERT INTO EXPENSETRACKER.CURRENCY(CURRSYMB, CURRTXT) VALUES ('$', 'USD');
INSERT INTO EXPENSETRACKER.CURRENCY(CURRSYMB, CURRTXT) VALUES ('₹', 'INR');
INSERT INTO EXPENSETRACKER.CURRENCY(CURRSYMB, CURRTXT) VALUES ('£', 'GBP');
INSERT INTO EXPENSETRACKER.CURRENCY(CURRSYMB, CURRTXT) VALUES ('€', 'EUR');
/* CURRENCY - End */

