INSERT INTO EXPENSETRACKER.USERINFO(USERNAME, FIRSTNAME, LASTNAME, SEX, PASSWORD, EMAIL, ADDRESS, MOBILE, PROFILEPIC, ISADMIN, ISVERIFIED, ISFTLOGIN, ISLOCKED, ACTIVATIONKEY)
VALUES ('admin', 'Administrator', ' ', 'M', 'Seiko#1986', 'raevanblog@gmail.com', ' ', '9894362480', null, 'Y', 'Y', 'N', 'N', null);

/* INCOMETYPE  - Start */
INSERT INTO EXPENSETRACKER.INCOMETYPE(INCOMETYPE, DESCRIPTION) VALUES ('Salary', 'Salary');
INSERT INTO EXPENSETRACKER.INCOMETYPE(INCOMETYPE, DESCRIPTION) VALUES ('Business', 'Business');
INSERT INTO EXPENSETRACKER.INCOMETYPE(INCOMETYPE, DESCRIPTION) VALUES ('Gift', 'Gift');
INSERT INTO EXPENSETRACKER.INCOMETYPE(INCOMETYPE, DESCRIPTION) VALUES ('Others', 'Others');
/* INCOMETYPE  - End */


/* EXPENSETYPE - Start */
INSERT INTO EXPENSETRACKER.EXPENSETYPE(EXPTYPE, DESCRIPTION) VALUES ('Cash', 'Cash');
INSERT INTO EXPENSETRACKER.EXPENSETYPE(EXPTYPE, DESCRIPTION) VALUES ('Credit Card', 'Credit Card');
INSERT INTO EXPENSETRACKER.EXPENSETYPE(EXPTYPE, DESCRIPTION) VALUES ('Debit Card', 'Debit Card');
INSERT INTO EXPENSETRACKER.EXPENSETYPE(EXPTYPE, DESCRIPTION) VALUES ('Net Banking', 'Net Banking');
/* EXPENSETYPE - End */

/* CURRENCY - Start */
INSERT INTO EXPENSETRACKER.CURRENCY(CURRSYMB, CURRTXT) VALUES ('$', 'USD');
INSERT INTO EXPENSETRACKER.CURRENCY(CURRSYMB, CURRTXT) VALUES ('₹', 'INR');
INSERT INTO EXPENSETRACKER.CURRENCY(CURRSYMB, CURRTXT) VALUES ('£', 'GBP');
INSERT INTO EXPENSETRACKER.CURRENCY(CURRSYMB, CURRTXT) VALUES ('€', 'EUR');
/* CURRENCY - End */

/* UNITS - Start */

INSERT INTO EXPENSETRACKER.UNITS(UNIT, DESCRIPTION) VALUES ('g','Gram');
INSERT INTO EXPENSETRACKER.UNITS(UNIT, DESCRIPTION) VALUES ('kg','Kilogram');
INSERT INTO EXPENSETRACKER.UNITS(UNIT, DESCRIPTION) VALUES ('ml','Millilitre');
INSERT INTO EXPENSETRACKER.UNITS(UNIT, DESCRIPTION) VALUES ('l','Litre');
INSERT INTO EXPENSETRACKER.UNITS(UNIT, DESCRIPTION) VALUES ('cm','Centimeter');
INSERT INTO EXPENSETRACKER.UNITS(UNIT, DESCRIPTION) VALUES ('km','Kilometer');
INSERT INTO EXPENSETRACKER.UNITS(UNIT, DESCRIPTION) VALUES ('qty','Quantity');

/* UNITS - End */

/*EXPENSECATEGORY - Start */
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Grocery', 'Grocery, Fruits', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Food', 'Food, Restaurent', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Shelter', 'Rent, Property Tax', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Utilities', 'Electricity, Water, Telephone, Cable, Internet', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Clothing', 'Clothing', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Transporation', 'Fuel, Tires, Vehicle Maintenance', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Medical', 'Medications, Doctor Fee', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Insurance', 'Auto Insurance, Life Insurance', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Electronics', 'TV, Washing Machine, XBOX, Play Station', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Spiritual', 'Temple Tickets, Donations', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Household Maintenance', 'House Repair, AC Service, TV Repair', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Household Supplies', 'Toiletries, Cleaning Supplies, Detergent, Tools', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Self Care', 'Gym Membership, Hair Cuts, Cosmetics', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Education', 'College, School, School Supplies', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Savings', 'Investment, Fixed Deposit', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Gift', 'Birthday, Anniversary Gifts', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Entertainment', 'Movie, Games, Music, Online Video Subscriptions', 'admin', 'N');
INSERT INTO EXPENSETRACKER.EXPENSE_CATEGORY(CATEGORY, DESCRIPTION, USERNAME, ISEDITABLE) VALUES ('Payments', 'Payment for Credit Card, Personal Loan, Car Loan', 'admin', 'N');

/*EXPENSECATEGORY - End */