DROP TABLE EXPENSETRACKER.INCOME;
DROP TABLE EXPENSETRACKER.INCOMETYPE;
DROP TABLE EXPENSETRACKER.INVENTORY;
DROP TABLE EXPENSETRACKER.EXPENSE;
DROP TABLE EXPENSETRACKER.UNITS;
DROP TABLE EXPENSETRACKER.EXPENSETYPE;
DROP TABLE EXPENSETRACKER.EXPENSE_CATEGORY;
DROP TABLE EXPENSETRACKER.MESSAGE;
DROP TABLE EXPENSETRACKER.QUERY;
DROP TABLE EXPENSETRACKER.USER_SETTINGS;
DROP TABLE EXPENSETRACKER.CURRENCY;
DROP TABLE EXPENSETRACKER.USERINFO;

DROP SCHEMA EXPENSETRACKER;