CREATE SCHEMA EXPENSETRACKER;

CREATE TABLE EXPENSETRACKER.USERINFO(
	USERNAME VARCHAR(25) PRIMARY KEY,
	FIRSTNAME VARCHAR(30) NOT NULL,
	LASTNAME VARCHAR(30) NOT NULL,
	SEX VARCHAR(1) DEFAULT 'M',	
	PASSWORD VARCHAR(25) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(200) NOT NULL,
	MOBILE VARCHAR(10),
	PROFILEPIC LONGTEXT,	
	ISADMIN VARCHAR(1) DEFAULT 'N',
	ISVERIFIED VARCHAR(1)  DEFAULT 'N',
	ISFTLOGIN VARCHAR(1) DEFAULT 'Y',
	ISLOCKED VARCHAR(1) DEFAULT 'N',
	ACTIVATIONKEY VARCHAR(25)
);

CREATE TABLE EXPENSETRACKER.CURRENCY (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	CURRSYMB VARCHAR(3) NOT NULL,
	CURRTXT VARCHAR(3) NOT NULL
);

CREATE TABLE EXPENSETRACKER.USER_SETTINGS (
	USERNAME VARCHAR(25) PRIMARY KEY,
	CURRENCY BIGINT NOT NULL,
	RCVRYEMAIL VARCHAR(50) NOT NULL,
	CONSTRAINT fk_settings_username FOREIGN KEY(USERNAME) REFERENCES EXPENSETRACKER.USERINFO(USERNAME),	
	CONSTRAINT fk_settings_currency FOREIGN KEY(CURRENCY) REFERENCES EXPENSETRACKER.CURRENCY(ID)
);

CREATE TABLE EXPENSETRACKER.MESSAGE (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	MSGTO VARCHAR(25) NOT NULL,
	MSGFROM VARCHAR(25) NOT NULL,
	MSGDATE TIMESTAMP NOT NULL,
	SUBJECT VARCHAR(200) NOT NULL,
	MESSAGE LONGTEXT NOT NULL,
	ISNEW CHAR(1) DEFAULT 'Y',
	CONSTRAINT fk_message_msgto FOREIGN KEY(MSGTO) REFERENCES EXPENSETRACKER.USERINFO(USERNAME),
	CONSTRAINT fk_message_msgfrom FOREIGN KEY(MSGFROM) REFERENCES EXPENSETRACKER.USERINFO(USERNAME)	
);

CREATE TABLE EXPENSETRACKER.QUERY (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	MSGFROM VARCHAR(60) NOT NULL,
	MSGDATE TIMESTAMP NOT NULL,
	SUBJECT VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	MESSAGE LONGTEXT NOT NULL,
	ISNEW CHAR(1) DEFAULT 'Y'
);


CREATE TABLE EXPENSETRACKER.EXPENSE_CATEGORY (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	CATEGORY VARCHAR(100) NOT NULL,
	USERNAME VARCHAR(25) NOT NULL,
	DESCRIPTION VARCHAR(100),
	CONSTRAINT fk_category_username FOREIGN KEY(USERNAME) REFERENCES EXPENSETRACKER.USERINFO(USERNAME)	
);

CREATE TABLE EXPENSETRACKER.EXPENSE(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	ITEMNAME VARCHAR(100) NOT NULL,
	EXPDATE DATE NOT NULL,
	USERNAME VARCHAR(25) NOT NULL,
	CATEGORY VARCHAR(100) NOT NULL,
	EXPTYPE VARCHAR(25) NOT NULL,
	QTY FLOAT NOT NULL,
	UNIT VARCHAR(6),
	PRICE FLOAT NOT NULL,
	PRICEPERUNIT FLOAT NOT NULL,	
	CONSTRAINT fk_expense_username FOREIGN KEY(USERNAME) references EXPENSETRACKER.USERINFO(USERNAME)
);

CREATE TABLE EXPENSETRACKER.UNITS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UNIT VARCHAR(6) NOT NULL,
    DESCRIPTION VARCHAR(50)    
);


CREATE TABLE EXPENSETRACKER.EXPENSETYPE(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	EXPTYPE VARCHAR(25) NOT NULL,
	DESCRIPTION VARCHAR(50)
);

CREATE TABLE EXPENSETRACKER.INCOME (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(25) NOT NULL,
	MTH INTEGER NOT NULL,
	YR INTEGER NOT NULL,
	INCOMETYPE VARCHAR(25) NOT NULL,
	INCOME DOUBLE DEFAULT 0.0 NOT NULL,
	CONSTRAINT pk_income PRIMARY KEY(INCOMETYPE, MTH, YR, USERNAME),
    CONSTRAINT fk_income_username FOREIGN KEY(USERNAME) REFERENCES EXPENSETRACKER.USERINFO(USERNAME),
    KEY(id)
);

CREATE TABLE EXPENSETRACKER.INVENTORY (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	ITEMNAME VARCHAR(100) NOT NULL,
	CATEGORY VARCHAR(100) NOT NULL,
	QTY FLOAT NOT NULL,
	UNIT VARCHAR(6),	
	USERNAME VARCHAR(25) NOT NULL,
	CONSTRAINT fk_inventory_username FOREIGN KEY(USERNAME) REFERENCES EXPENSETRACKER.USERINFO(USERNAME)	
);

CREATE TABLE EXPENSETRACKER.INCOMETYPE(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	INCOMETYPE VARCHAR(25) NOT NULL,
	DESCRIPTION VARCHAR(50)
);