CREATE SCHEMA EXPENSETRACKER;

CREATE TABLE EXPENSETRACKER.USERINFO(
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
SEX VARCHAR(1) DEFAULT 'M',
USERNAME VARCHAR(25) PRIMARY KEY,
PASSWORD VARCHAR(25) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
MOBILE VARCHAR(10),
ADDRESS VARCHAR(200)
);

CREATE TABLE EXPENSETRACKER.USER_PERMISSION(
USERNAME VARCHAR(25) PRIMARY KEY,
ISADMIN BOOLEAN,
ISVERIFIED BOOLEAN,
FOREIGN KEY(USERNAME) REFERENCES EXPENSETRACKER.USERINFO(USERNAME)
);

CREATE TABLE EXPENSETRACKER.EXPENSE_CATEGORY (
		CATEGORYID INTEGER AUTO_INCREMENT PRIMARY KEY,
		CATEGORY VARCHAR(100) NOT NULL,
		DESCRIPTION VARCHAR(100)
		
);

CREATE TABLE EXPENSETRACKER.EXPENSE(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
ITEMNAME VARCHAR(100) NOT NULL,
EXPDATE DATE NOT NULL,
USERNAME VARCHAR(25) NOT NULL,
CATEGORY VARCHAR(100) NOT NULL,
EXPTYPE VARCHAR(25) NOT NULL,
QTY FLOAT NOT NULL,
PRICE FLOAT NOT NULL,
PRICEPERUNIT FLOAT NOT NULL,
constraint fk_expense foreign key(username) references EXPENSETRACKER.userinfo(username)
);

CREATE TABLE EXPENSETRACKER.EXPENSETYPE(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
EXPTYPE VARCHAR(25),
DESCRIPTION VARCHAR(50)
);

CREATE TABLE EXPENSETRACKER.INCOME (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(25) NOT NULL,
	MTH INTEGER NOT NULL,
	YR INTEGER NOT NULL,
	INCOMETYPE VARCHAR(25) NOT NULL,
	INCOME DOUBLE DEFAULT 0.0 NOT NULL,
	constraint pk_income primary key(INCOMETYPE, MTH, YR),
    constraint fk_income foreign key(username) references EXPENSETRACKER.userinfo(username),
    key(id)
);

CREATE TABLE EXPENSETRACKER.INCOMETYPE(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
INCOMETYPE VARCHAR(25),
DESCRIPTION VARCHAR(50)
);

DROP TABLE EXPENSETRACKER.INCOME;
DROP TABLE EXPENSETRACKER.INCOMETYPE;
DROP TABLE EXPENSETRACKER.EXPENSE;
DROP TABLE EXPENSETRACKER.EXPENSETYPE;
DROP TABLE EXPENSETRACKER.EXPENSE_CATEGORY;
DROP TABLE EXPENSETRACKER.USER_PERMISSION;
DROP TABLE EXPENSETRACKER.USERINFO;
