--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "EXPENSETRACKER"."EXPENSE_CATEGORY" DROP CONSTRAINT "SQL160906142115870";

DROP INDEX "EXPENSETRACKER"."SQL160906142115870";

DROP TABLE "EXPENSETRACKER"."EXPENSE_CATEGORY";

CREATE TABLE "EXPENSETRACKER"."EXPENSE_CATEGORY" (
		"CATEGORY_ID" INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"CATEGORY" VARCHAR(200),
		"DESCRIPTION" VARCHAR(200)
	);

CREATE UNIQUE INDEX "EXPENSETRACKER"."SQL160906142115870" ON "EXPENSETRACKER"."EXPENSE_CATEGORY" ("CATEGORY_ID" ASC);

ALTER TABLE "EXPENSETRACKER"."EXPENSE_CATEGORY" ADD CONSTRAINT "SQL160906142115870" PRIMARY KEY ("CATEGORY_ID");

