--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "EXPENSETRACKER"."EXPENSE_CATEGORY" (
		"CATEGORYID" INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"CATEGORY" VARCHAR(200),
		"DESCRIPTION" VARCHAR(200)
	);

CREATE UNIQUE INDEX "EXPENSETRACKER"."SQL160918095235170" ON "EXPENSETRACKER"."EXPENSE_CATEGORY" ("CATEGORYID" ASC);

CREATE UNIQUE INDEX "EXPENSETRACKER"."SQL160906194159040" ON "EXPENSETRACKER"."EXPENSE_CATEGORY" ("CATEGORYID" ASC);

ALTER TABLE "EXPENSETRACKER"."EXPENSE_CATEGORY" ADD CONSTRAINT "SQL160906194159040" PRIMARY KEY ("CATEGORYID");

